### ISSUE TITLE
Segmentation Fault after execution

### ISSUE THREAD

**Issue by misterspock1** [SMerrony/dashera#1]
Program seems to build with and without optimizations but executing "./dashera" results in a "segmentation fault." Running Ubuntu 20.04.4 LTS on 32-bit ARM. Any guidance would be appreciated!

**Comment by SMerrony** [comment]
I don't have access to this type of environment.  Are you getting _any_ of the initial `DEBUG: ` lines on stdout before it crashes?

**Comment by misterspock1** [comment]
It just dumps segmentation fault to screen right after running, no other information.

**Comment by SMerrony** [comment]
I can't find any evidence that GtkAda is supported on 32-bit ARM.

According to the GitHub page for GtkAda https://github.com/AdaCore/gtkada

```
This library has been tested using Gtk+ 3.14.15 on the following systems:

    GNU Linux/x86
    GNU Linux/x86-64
    Solaris/sparc
    Windows 7, 8.1 and 10
```

Have you built it yourself?  
Does the `testgtk` program run?

**Comment by misterspock1** [comment]
I installed it with the repo:
**misterspock1@localhost:~$ sudo apt search libgtkada19-dev
Sorting... Done
Full Text Search... Done
libgtkada19-dev/focal,now 19-4 armhf [installed]
  Ada binding for the GTK+ GUI (development files)_**
Also checked:
**misterspock1@localhost:~$ dpkg -l libgtk2.0-0 libgtk-3-0
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name              Version            Architecture Description
+++-=================-==================-============-==================================================
ii  libgtk-3-0:armhf  3.24.20-0ubuntu1.1 armhf        GTK graphical user interface library
ii  libgtk2.0-0:armhf 2.24.32-4ubuntu4   armhf        GTK graphical user interface library - old version**

I don't know where to find testgtk, I did test GTK itself by installing geany, which is another GTK program and it worked fine. 

Thanks for taking the time to look at my issues!

**Comment by SMerrony** [comment]
Sorry, but I don't think I can help any more with this.
If there were no errors from the `gprbuild` command then it seems likely something is wrong with your environment.
Does `ldd dashera` produce any errors?

**Comment by misterspock1** [comment]
**misterspock1@localhost:~/dasher/dashera$ ldd dashera
        linux-vdso.so.1 (0xbef9b000)
        /support/libdisableselinux.so (0xa96f7000)
        libgtkada.so.19 => /usr/lib/arm-linux-gnueabihf/libgtkada.so.19 (0xa8fd2000)
        libgtk-3.so.0 => /usr/lib/arm-linux-gnueabihf/libgtk-3.so.0 (0xa8a42000)
        libgdk-3.so.0 => /usr/lib/arm-linux-gnueabihf/libgdk-3.so.0 (0xa8991000)
        libcairo.so.2 => /usr/lib/arm-linux-gnueabihf/libcairo.so.2 (0xa88d4000)
        libgobject-2.0.so.0 => /usr/lib/arm-linux-gnueabihf/libgobject-2.0.so.0 (0xa8883000)
        libglib-2.0.so.0 => /usr/lib/arm-linux-gnueabihf/libglib-2.0.so.0 (0xa879b000)
        libgthread-2.0.so.0 => /usr/lib/arm-linux-gnueabihf/libgthread-2.0.so.0 (0xa8789000)
        libgnarl-9.so.1 => /usr/lib/arm-linux-gnueabihf/libgnarl-9.so.1 (0xa8744000)
        libgnat-9.so.1 => /usr/lib/arm-linux-gnueabihf/libgnat-9.so.1 (0xa84f0000)
        libgcc_s.so.1 => /usr/lib/arm-linux-gnueabihf/libgcc_s.so.1 (0xa84c7000)
        libc.so.6 => /usr/lib/arm-linux-gnueabihf/libc.so.6 (0xa83c8000)
        libpangocairo-1.0.so.0 => /lib/arm-linux-gnueabihf/libpangocairo-1.0.so.0 (0xa83a5000)
        libpango-1.0.so.0 => /lib/arm-linux-gnueabihf/libpango-1.0.so.0 (0xa8362000)
        libgdk_pixbuf-2.0.so.0 => /lib/arm-linux-gnueabihf/libgdk_pixbuf-2.0.so.0 (0xa8337000)
        libgio-2.0.so.0 => /lib/arm-linux-gnueabihf/libgio-2.0.so.0 (0xa8207000)
        libgmodule-2.0.so.0 => /lib/arm-linux-gnueabihf/libgmodule-2.0.so.0 (0xa81f4000)
        libfontconfig.so.1 => /lib/arm-linux-gnueabihf/libfontconfig.so.1 (0xa81b7000)
        libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0xa814e000)
        libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0xa8126000)
        /lib/ld-linux-armhf.so.3 (0x0f000000)
        libX11.so.6 => /lib/arm-linux-gnueabihf/libX11.so.6 (0xa8033000)
        libXi.so.6 => /lib/arm-linux-gnueabihf/libXi.so.6 (0xa8019000)
        libXfixes.so.3 => /lib/arm-linux-gnueabihf/libXfixes.so.3 (0xa8005000)
        libcairo-gobject.so.2 => /lib/arm-linux-gnueabihf/libcairo-gobject.so.2 (0xa7fef000)
        libatk-1.0.so.0 => /lib/arm-linux-gnueabihf/libatk-1.0.so.0 (0xa7fc6000)
        libatk-bridge-2.0.so.0 => /lib/arm-linux-gnueabihf/libatk-bridge-2.0.so.0 (0xa7f94000)
        libepoxy.so.0 => /lib/arm-linux-gnueabihf/libepoxy.so.0 (0xa7ecc000)
        libfribidi.so.0 => /lib/arm-linux-gnueabihf/libfribidi.so.0 (0xa7ea3000)
        libpangoft2-1.0.so.0 => /lib/arm-linux-gnueabihf/libpangoft2-1.0.so.0 (0xa7e85000)
        libharfbuzz.so.0 => /lib/arm-linux-gnueabihf/libharfbuzz.so.0 (0xa7dc5000)
        libfreetype.so.6 => /lib/arm-linux-gnueabihf/libfreetype.so.6 (0xa7d43000)
        libXinerama.so.1 => /lib/arm-linux-gnueabihf/libXinerama.so.1 (0xa7d31000)
        libXrandr.so.2 => /lib/arm-linux-gnueabihf/libXrandr.so.2 (0xa7d1a000)
        libXcursor.so.1 => /lib/arm-linux-gnueabihf/libXcursor.so.1 (0xa7d03000)
        libXcomposite.so.1 => /lib/arm-linux-gnueabihf/libXcomposite.so.1 (0xa7cf1000)
        libXdamage.so.1 => /lib/arm-linux-gnueabihf/libXdamage.so.1 (0xa7cdf000)
        libxkbcommon.so.0 => /lib/arm-linux-gnueabihf/libxkbcommon.so.0 (0xa7c9f000)
        libwayland-cursor.so.0 => /lib/arm-linux-gnueabihf/libwayland-cursor.so.0 (0xa7c88000)
        libwayland-egl.so.1 => /lib/arm-linux-gnueabihf/libwayland-egl.so.1 (0xa7c76000)
        libwayland-client.so.0 => /lib/arm-linux-gnueabihf/libwayland-client.so.0 (0xa7c5d000)
        libXext.so.6 => /lib/arm-linux-gnueabihf/libXext.so.6 (0xa7c40000)
        librt.so.1 => /lib/arm-linux-gnueabihf/librt.so.1 (0xa7c2a000)
        libpixman-1.so.0 => /lib/arm-linux-gnueabihf/libpixman-1.so.0 (0xa7ba1000)
        libpng16.so.16 => /lib/arm-linux-gnueabihf/libpng16.so.16 (0xa7b6f000)
        libxcb-shm.so.0 => /lib/arm-linux-gnueabihf/libxcb-shm.so.0 (0xa7b5c000)
        libxcb.so.1 => /lib/arm-linux-gnueabihf/libxcb.so.1 (0xa7b33000)
        libxcb-render.so.0 => /lib/arm-linux-gnueabihf/libxcb-render.so.0 (0xa7b1a000)
        libXrender.so.1 => /lib/arm-linux-gnueabihf/libXrender.so.1 (0xa7b03000)
        libz.so.1 => /lib/arm-linux-gnueabihf/libz.so.1 (0xa7ae0000)
        libffi.so.7 => /lib/arm-linux-gnueabihf/libffi.so.7 (0xa7aca000)
        libpcre.so.3 => /lib/arm-linux-gnueabihf/libpcre.so.3 (0xa7a6a000)
        libthai.so.0 => /lib/arm-linux-gnueabihf/libthai.so.0 (0xa7a53000)
        libdl.so.2 => /lib/arm-linux-gnueabihf/libdl.so.2 (0xa7a40000)
        libmount.so.1 => /lib/arm-linux-gnueabihf/libmount.so.1 (0xa79f2000)
        libselinux.so.1 => /lib/arm-linux-gnueabihf/libselinux.so.1 (0xa79c8000)
        libresolv.so.2 => /lib/arm-linux-gnueabihf/libresolv.so.2 (0xa79a8000)
        libexpat.so.1 => /lib/arm-linux-gnueabihf/libexpat.so.1 (0xa797f000)
        libuuid.so.1 => /lib/arm-linux-gnueabihf/libuuid.so.1 (0xa7969000)
        libdbus-1.so.3 => /lib/arm-linux-gnueabihf/libdbus-1.so.3 (0xa7929000)
        libatspi.so.0 => /lib/arm-linux-gnueabihf/libatspi.so.0 (0xa78f7000)
        libgraphite2.so.3 => /lib/arm-linux-gnueabihf/libgraphite2.so.3 (0xa78cb000)
        libXau.so.6 => /lib/arm-linux-gnueabihf/libXau.so.6 (0xa78b8000)
        libXdmcp.so.6 => /lib/arm-linux-gnueabihf/libXdmcp.so.6 (0xa78a4000)
        libdatrie.so.1 => /lib/arm-linux-gnueabihf/libdatrie.so.1 (0xa7890000)
        libblkid.so.1 => /lib/arm-linux-gnueabihf/libblkid.so.1 (0xa784a000)
        libpcre2-8.so.0 => /lib/arm-linux-gnueabihf/libpcre2-8.so.0 (0xa77d8000)
        libsystemd.so.0 => /lib/arm-linux-gnueabihf/libsystemd.so.0 (0xa7753000)
        libbsd.so.0 => /lib/arm-linux-gnueabihf/libbsd.so.0 (0xa7730000)
        liblzma.so.5 => /lib/arm-linux-gnueabihf/liblzma.so.5 (0xa7704000)
        liblz4.so.1 => /lib/arm-linux-gnueabihf/liblz4.so.1 (0xa76de000)
        libgcrypt.so.20 => /lib/arm-linux-gnueabihf/libgcrypt.so.20 (0xa762b000)
        libgpg-error.so.0 => /lib/arm-linux-gnueabihf/libgpg-error.so.0 (0xa7606000)**

That's a long one, don't know if it helps. Thanks for your help. I'll probably just give this a try on x64 Linux, but maybe someone else will see it, and think of something. Great project. Not many programs support the Dasher terminal, I think.

**Comment by SMerrony** [comment]
Well there are no errors showing with `ldd`.

I just successfully built and ran v0.11.1 (a small change for GNAT 10) on a QEMU PI 2 (ARM-32) emulator.  The system is running the latest Raspberry OS ("bullseye").

I'm quite pleased that worked!

OK if I close this for now?

**Comment by misterspock1** [comment]
That's fine! Thanks for the help, glad to see it runs on a pi. I'm running in a CHROOT, so I'm wondering if that might be part of the problem.
